on:
  schedule:
  - cron: '0 * * * *'

jobs:
  pull-changes:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull changes from main branch
        run: |
          git checkout backup-branch
          git pull origin main
          git push origin backup-branch

