name: Assign Label to Assigned Issues

on:
  issues:
    types:
      - assigned

jobs:
  assign-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const labelToAdd = '🚧STATUS : in progress';
            const labelToRemove = '⏳STATUS : waiting for triage';
            const labelToRemove2 = '👍STATUS : ready to assign';
            
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: [labelToAdd],
            });
            
            const labelExists = await github.issues.getLabel({

                owner: context.repo.owner,

                repo: context.repo.repo,

                name: labelToRemove,

              }).catch(() => false);
              
              const labelExists2 = await github.issues.getLabel({

                owner: context.repo.owner,

                repo: context.repo.repo,

                name: labelToRemove2,
                }).catch(() => false);
              
             if (labelExists) { 
               await github.issues.removeLabel({

                owner: context.repo.owner,

                repo: context.repo.repo,

                issue_number: issue.number,

                name: labelToRemove,
              });
            }
            
            if (labelExists2) {
              await github.issues.removeLabel({

               owner: context.repo.owner,

               repo: context.repo.repo,

                issue_number: issue.number,

                name: labelToRemove2,
            });


