name: Update Issue Label when assigned 

on:
  issues:
    types:
      - assigned

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Update Issue Label
        uses: peter-evans/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
